import { TopBar, Footer } from "@/components/Chrome";

export const metadata = { title: "Términos y condiciones — ANTENA MUSICAL" };

const sections = [
  ["1. Aceptación y cuenta", "Al crear una cuenta, usar una estación o publicar contenido en ANTENA MUSICAL aceptas estos términos. Debes proporcionar datos correctos y proteger tu contraseña. Eres responsable de toda actividad que ocurra desde tu cuenta. Si actúas en nombre de una banda, sello o colectivo, declaras contar con autorización suficiente para hacerlo."],
  ["2. Tu contenido y tus derechos", "Conservas la propiedad de tus textos, fotos, enlaces, biografía, letras y demás contenido. Al publicarlo nos otorgas una licencia limitada, no exclusiva, mundial y sin regalías únicamente para alojar referencias, mostrar, adaptar técnicamente y distribuir ese contenido dentro de ANTENA MUSICAL y sus funciones de promoción. Declaras que tienes todos los derechos, licencias y permisos necesarios sobre lo que subes o enlazas."],
  ["3. Música, imágenes y enlaces de terceros", "ANTENA MUSICAL no aloja archivos de música ni, para imágenes nuevas, archivos fotográficos: enlaza plataformas como YouTube, Spotify, SoundCloud, Deezer y Google Drive. Cada persona es responsable de que sus enlaces públicos, imágenes, samples, letras, videos y créditos no infrinjan derechos de autor, marcas, privacidad o derechos de terceros. Los términos de cada plataforma enlazada también aplican."],
  ["4. Conducta prohibida", "No puedes publicar material ilegal, infractor, engañoso, de explotación, de odio, amenazante, sexual no autorizado, que doxxee a alguien, spam, malware ni suplantaciones. Tampoco puedes manipular reproducciones, atacar la infraestructura o usar el chat para acosar. No toleramos contenido que promueva daño real o viole la ley aplicable."],
  ["5. Moderación, retiro y expulsión", "Podemos investigar, ocultar, retirar, desindexar o eliminar contenido; limitar funciones; suspender estaciones; cerrar cuentas; o colaborar con autoridades cuando sea razonablemente necesario para proteger a la comunidad, responder a reclamaciones, cumplir la ley o aplicar estos términos. Podemos actuar sin aviso previo ante riesgo urgente. Cuando sea posible, dejaremos una nota de moderación y ofreceremos un canal de revisión."],
  ["6. Reclamaciones de derechos de autor", "Si consideras que algún contenido infringe tus derechos, envía una notificación con: identificación de la obra, URL exacta del contenido cuestionado, tus datos de contacto, declaración de buena fe y declaración de exactitud bajo responsabilidad. Los artistas pueden responder con una contranotificación si consideran que hubo un error. Conservaremos registros razonables de estas gestiones."],
  ["7. Servicios de terceros y disponibilidad", "La reproducción, widgets, enlaces, Drive, correo y calendarios dependen de servicios de terceros. ANTENA MUSICAL no garantiza disponibilidad ininterrumpida ni que un enlace externo permanezca activo. Podemos cambiar, limitar o descontinuar funcionalidades. La plataforma se ofrece «tal cual» dentro de lo permitido por la ley."],
  ["8. Limitación de responsabilidad", "En la máxima medida permitida por la ley, ANTENA MUSICAL no es responsable de contenido publicado por usuarios, pérdidas derivadas de enlaces de terceros, decisiones de contratación, daños indirectos ni conflictos entre miembros de la comunidad. Nada de estos términos excluye responsabilidad que no pueda excluirse legalmente."],
  ["9. Cambios y contacto", "Podemos actualizar estos términos cuando cambie el servicio o la normativa. Publicaremos la versión vigente aquí. Para soporte, reclamaciones o apelaciones de moderación, utiliza el canal de contacto indicado en la plataforma."],
];

export default function TermsPage() {
  return <div className="min-h-screen"><TopBar solid /><main className="mx-auto max-w-3xl px-4 pt-14 pb-8"><p className="font-tech text-[11px] tracking-[0.3em] uppercase text-signal mb-3">Marco de la comunidad</p><h1 className="font-display font-extrabold text-4xl md:text-6xl tracking-tight">Términos y condiciones<span className="text-signal">.</span></h1><p className="mt-5 text-bone-dim leading-relaxed">Última actualización: 13 de agosto de 2026. Este texto es una base operativa para ANTENA MUSICAL y no sustituye asesoría jurídica profesional local.</p><div className="mt-10 space-y-8">{sections.map(([title, body]) => <section key={title} className="border-l-2 border-signal pl-5"><h2 className="font-display font-extrabold text-xl mb-2">{title}</h2><p className="text-sm text-bone-dim leading-relaxed">{body}</p></section>)}</div></main><Footer /></div>;
}
